export const SHOW_FASTEST_RESULTS = 'SHOW_FASTEST_RESULTS';
export type SHOW_FASTEST_RESULTS = typeof SHOW_FASTEST_RESULTS;

export const SHOW_CHEAPEST_RESULTS = 'SHOW_CHEAPEST_RESULTS';
export type SHOW_CHEAPEST_RESULTS = typeof SHOW_CHEAPEST_RESULTS;

export const HIDE_RESULTS = 'HIDE_RESULTS';
export type HIDE_RESULTS = typeof HIDE_RESULTS;

export const FETCH_DEALS = 'FETCH_DEALS';
export type FETCH_DEALS = typeof FETCH_DEALS;
